### ISSUE TITLE
No radiosonde plugin in Mac (Intel) Build

### ISSUE THREAD

**Issue by drdatapi** [jethrocarr/SDRPlusPlus#4]
The radiosonde Plugin is not included in the App for MacOS Intel.

<img width="781" alt="Bildschirmfoto 2023-01-26 um 19 32 02" src="https://user-images.githubusercontent.com/77466997/214920533-d6f56b7a-a840-49eb-8c34-d2cb932ec3e3.png">

**Comment by jethrocarr** [comment]
This should now be fixed in master and available for download in the nightly release.
